package com.ssy.srouter.utils;

public class Consts {


    // Generate
    public static final String SEPARATOR = "$$";
    public static final String PROJECT = "SRouter";
    public static final String TAG = PROJECT + "::";
    public static final String NAME_OF_GROUP = PROJECT + SEPARATOR + "Group" + SEPARATOR;
    public static final String NAME_OF_PROVIDER = PROJECT + SEPARATOR + "Providers"+SEPARATOR;
    public static final String NAME_OF_INTERCEPTOR = PROJECT + SEPARATOR + "Interceptors"+SEPARATOR;
    public static final String PACKAGE_OF_GENERATE_FILE = "com.ssy.srouter.routes";
    public static final String WARNING_TIPS = "DO NOT EDIT THIS FILE!!! IT WAS GENERATED BY SROUTER.";
    public static final String NAME_OF_ROOT = PROJECT + SEPARATOR + "Root";


    private static final String PACKAGE = "com.ssy.srouter";
    private static final String TEMPLATE_PACKAGE = ".template";
    public static final String IROUTE_GROUP = PACKAGE + ".api" + TEMPLATE_PACKAGE + ".IRouteGroup";
    public static final String IPROVIDER_GROUP =PACKAGE+ ".api"  + TEMPLATE_PACKAGE + ".IProviderGroup";
    public static final String IINTERCEPTION_GROUP = PACKAGE + ".api" + TEMPLATE_PACKAGE + ".IInterceptionGroup";
    public static final String IINTERCEPTOR = PACKAGE + ".api" + TEMPLATE_PACKAGE + ".IInterceptor";
    public static final String ITROUTE_ROOT = PACKAGE + ".api"+ TEMPLATE_PACKAGE + ".IRouteRoot";
    public static final String IPROVIDER = PACKAGE + ".api"+TEMPLATE_PACKAGE + ".IProvider";
    public static final String METHOD_LOAD_INTO = "loadInto";



    // Log
    static final String PREFIX_OF_LOGGER = PROJECT + "::Compiler ";


    public static final String ANNOTATION_TYPE_ROUTE = PACKAGE + ".annotation.Route";


    // System interface
    public static final String ACTIVITY = "android.app.Activity";
    public static final String FRAGMENT = "android.app.Fragment";
    public static final String FRAGMENT_V4 = "android.support.v4.app.Fragment";
    public static final String SERVICE = "android.app.Service";
    public static final String PARCELABLE = "android.os.Parcelable";

}
